### ISSUE TITLE
smart_crossfade not working

### ISSUE THREAD

**Issue by AJDurant** [UniversityRadioYork/jukebox#1]
I think this is probably due to savonet/liquidsoap#98 so we will need to either build the git source or wait for the next point release.

moved from UniversityRadioYork/Issues#37

**Comment by LloydW93** [comment]
Woo, back to git source! Given that was fixed in 2013 I'm guessing they aren't releasing particularly frequently atm.

**Comment by AJDurant** [comment]
we are now on git source so will have to see if this is fixed. I haven't really been paying attention
